title: Northwind Company Analysis
description: SQL, data modeling, and BI case study by Abdullah Subuh
theme: jekyll-theme-midnight   # dark, simple, easy to read
markdown: kramdown
highlighter: rouge

