title: Northwind Company Analysis
description: SQL, data modeling, and BI case study by Abdullah Subuh
remote_theme: andrewbanchich/vscode-dark-plus-jekyll
plugins:
  - jekyll-remote-theme
markdown: kramdown
highlighter: rouge
