title: British Airways Tableau Dashboard
description: Tableau analysis and KPI dashboard by Abdullah Subuh
theme: jekyll-theme-slate   # Base theme
markdown: kramdown
highlighter: rouge

sass:
  sass_dir: assets/css
